baseurl = "https://krishxmatta.dev/"
theme = "krishxmatta.dev"

[[menu.main]]
name = "Site"
url = "/site"
weight = 1

[[menu.main]]
name = "Me"
url = "/me"
weight = 2

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = ''
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    noHl = false
    style = ''
    tabWidth = ''