#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: 

#+TITLE: Me

#+HUGO_CUSTOM_FRONT_MATTER: :drop_cap false

#+OPTIONS: author:nil

I'm Krish Matta.

* Work
I'm a student at Carnegie Mellon University in Pittsburgh, Pennsylvania, majoring in computer science. I have worked for/collaborated with: NASA Goddard Space Flight Center (2022), University of Delaware Safro Research Group (2021 - 2023), and Roblox (2023).

* Personality 
I would describe myself as optimistic, introverted, and ambitious. My scores on the [[https://en.wikipedia.org/wiki/Big_Five_personality_traits][Big Five Personality personality traits]], according to [[https://yourmorals.org/][YourMorals]], are:
1. Openness: 74%.
2. Conscientiousness: 82%.
3. Extraversion: 25%.
4. Agreeableness: 56%.
5. Neuroticism: 42%.

* Interests
My academic interests are broad, spanning computer science, mathematics, philosophy, literature, and history. While most of my time is spent on computer science, I'm a strong proponent of the idea that one's knowledge should be "T-shaped," with the horizontal bar representing knowledge over a breadth of subjects and the vertical bar representing a large depth of knowledge in a single subject. Ultimately, I hope to contribute to the creation of safe artificial general intelligence.

On a more casual note, I also enjoy strategy games (particularly card games), puzzles, instrumental music, photography (nature, architectural, landscape), and gardening.

* Sites
- [[https://github.com/krishxmatta][GitHub]]
- [[https://www.linkedin.com/in/krishxmatta/][LinkedIn]]
- [[https://www.last.fm/user/krishmatta][Last.fm]]

* Contact
You may contact me via email at [[mailto:self@krishxmatta.dev][self@krishxmatta.dev]].
