#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: 

#+TITLE: Site

#+HUGO_CUSTOM_FRONT_MATTER: :drop_cap false

#+OPTIONS: author:nil

This site serves as both an outlet for me to haphazardly share my thoughts and an exercise to improve my writing style.

* Technical Aspects
** Hosting
This site is hosted on GitHub Pages, and consequently managed using git. Its repository is available [[https://github.com/krishxmatta/krishxmatta.dev/][here]].

** Workflow
[[https://gohugo.io/][Hugo]] is used as a static site generator to easily maintain fine-grained control over the site without having to directly manage its HTML. All content on the website originates as an Org file created in Emacs, as it is my preferred editor. All posts in their Org form are available in the [[https://github.com/krishxmatta/krishxmatta.dev/tree/main/content-org][content-org]] folder found in the site repository. The [[https://ox-hugo.scripter.co/][ox-hugo]] Emacs package is then used to convert Org files to Hugo-compatible Markdown. Once this Markdown is pushed to the main repository, a GitHub Action automatically deploys the site to [[https://krishxmatta.dev][krishxmatta.dev]].

I originally had hoped to use a Lisp-based static site generator such as [[https://dthompson.us/projects/haunt.html][Haunt]], but such tools proved to be cumbersome---hence, my current choice of Hugo. This selection is subject to change, however.

** Design
The site is designed to be minimal while maintaining some stylistic features to impart a distinctive touch. Ironically, many design choices are attributed to [[https://gwern.net/][Gwern]], but I hope to iteratively modify the style into my own. The appearance itself is managed with a [[https://github.com/krishxmatta/krishxmatta.dev/tree/main/themes/krishxmatta.dev][custom Hugo theme]].

* Updates
My thoughts and beliefs are constantly evolving as I continue to learn and encounter new ideas---consequently, this site is organic, meaning that it is subject to frequent change without prior warning. As such, I'm not entirely in favor of imposing chronological ordering on this site's posts, but it holds some conveniences that make it worth incorporating. The combination of frequent updates alongside chronological order can certainly cause confusion when reading posts, so to help ameliorate this issue I have included a changelog for the site below. For more detailed descriptions of each change made, please refer to the site repository's [[https://github.com/krishxmatta/krishxmatta.dev/commits/main][commit history]].
** Changelog
- 9/17/2023: Improve mobile layout
- 9/17/2023: Increase navigation link size
- 9/17/2023: Implemented changelog

* To-Do
Below is a list of everything I hope to eventually incorporate in the site.
** Features
- RSS feed integration
  
** Appearance
- Improved code blocks
- Improved post listing on homepage
- Pagination on homepage
- Improved blockquotes
  
** Articles
- Write an article regarding notes setup
- Write an article regarding productivity workflow
